### ISSUE TITLE
[Suggestion] 求改进

### ISSUE THREAD

**Issue by ddd354** [xinxin8816/gfriends#1]
原因参照：https://github.com/ddd354/JAVnfoMoviesImporter.bundle/pull/1/files

* 女优名字目测仅为日文，希望能在look up json支持中文/多语言
* 同一女优可以有多个名字，希望look up json能直接有最佳的一个，方便查找
* 希望能tag一下commit / release，方便刮削器versioning / debug

**Comment by xinxin8816** [comment]
1. 已察觉这个问题，有的图书馆搜刮到中文名导致不能匹配，但是通过机翻途径获得的多语言与实际不符，目前没有找到好的方法解决。
2. 同一女友可以有多个名字，也包括同一女友匹配多个头像的问题。因个人喜好不同与各来源站质量参差不齐，我推荐的解决方案是设置优先级加权匹配。
3. 还有一个网站 _ミニマム_ 的采集目前遇到一些问题，因个人时间问题暂无暇修复。打算采集完成后tag first version.

**Comment by xinxin8816** [comment]
close
