### ISSUE TITLE
希望提供并行下载

### ISSUE THREAD

**Issue by Elypha** [xinxin8816/gfriends#14]
您好，

希望可以通过并行下载来加快完成速度~~反正也是从github上拖~~。只是看到代码里有许多 exception handling & debug 的部分，考虑到开发者的时间，先做一个 testing 的 preview 也可以））

**Comment by xinxin8816** [comment]
ok，在做了 ~（进度0%）~

**Comment by xinxin8816** [comment]
@Elypha 测试版已推出：[Gfriends Inputer v2.6](https://github.com/xinxin8816/gfriends/releases/tag/v2.6)

**Comment by Elypha** [comment]
> @Elypha 测试版已推出：[Gfriends Inputer v2.6](https://github.com/xinxin8816/gfriends/releases/tag/v2.6)

感谢！测试了一下 windows build，下载方面没有问题，但是好像下载完成之后没导入到 Jellyfin 里（`metadata/People/` 下面是空的）

```
Gfriends Inputer v2.6
https://github.com/xinxin8816/gfriends
推荐开启全局代理以加快下载速度

Press any key to continue . . .
>> 读取 Emby / Jellyfin 演员...
>> 读取 Emby / Jellyfin 演员完成

>> 下载头像仓库文件树...
>> 读取头像仓库文件树完成
当前仓库头像数量：30889枚

>> 初始化下载...
[========================================] 1665/1665 [100%] in 0.3s (4857.14/s)

>> 尺寸优化...
[========================================] 1159/1159 [100%] in 0.2s (5662.62/s)
[========================================] 2/2 [100%] in 0.1s (19.88/s)

>> 导入头像...
[========================================] 1159/1159 [100%] in 0.4s (3000.01/s)
[========================================] 2/2 [100%] in 0.1s (19.88/s)

Emby / Jellyfin 拥有演员 1665 人，当前已有头像 0 人
本次成功导入 1158 人
仓库未收录 0 人
```

**Comment by xinxin8816** [comment]
我已经定位了 BUG，晚些修复

**Comment by xinxin8816** [comment]
@Elypha 该问题已经修复：[Gfriends Inputer v2.61](https://github.com/xinxin8816/gfriends/releases/tag/v2.61)

**Comment by Elypha** [comment]
我这边测试OK，目前没有发现其他问题

**Comment by xinxin8816** [comment]
正式版本已推出：[Gfriends Inputer v2.62](https://github.com/xinxin8816/gfriends/releases/tag/v2.62)
