### ISSUE TITLE
想求教一下这类软件的制作思路

### ISSUE THREAD

**Issue by Daasein** [xinxin8816/gfriends#16]
本人编程小白，还在学习中，想制作一个批量修改jellyfin中演员名字的小软件，但是不知道jellyfin和emby的api如何使用，看他们的文档中提供API又是针对插件开发的。所以想问一下通过url访问服务器数据的api的使用方法是怎么查到的，谢谢大佬！

**Comment by xinxin8816** [comment]
http://swagger.emby.media/
