### ISSUE TITLE
Mac版本本地头像不匹配，上传Jellyfin失败

### ISSUE THREAD

**Issue by lqxx2005** [xinxin8816/gfriends#20]
你好，我是在Mac系统上使用。我将自己的本地头像放到了自动生成的avatar文件夹，运行程序，上传Jellyfin,发现有本地头像的在Jellyfin都是空，上传失败。我猜测是Mac的本地文件命名和Jellyfin不匹配，导致上传失败。

**Comment by xinxin8816** [comment]
本地文件名称，必须和媒体服务器演员姓名完全一致，才能正常上传。
