### ISSUE TITLE
无法读取配置文件

### ISSUE THREAD

**Issue by lbbboy** [xinxin8816/gfriends#24]
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 153, in read_config
UnboundLocalError: local variable 'BD_AI_client' referenced before assignment

× 无法读取 config.ini。如果这是旧版本的配置文件，请删除后重试。

config.ini 已经删除过。

**Comment by xinxin8816** [comment]
已修复，请重新下载 Release
