### ISSUE TITLE
头像导入阶段意外中断

### ISSUE THREAD

**Issue by eternalfor** [xinxin8816/gfriends#25]
>> 下载头像...
!! ./Downloads/美倉あやみ.jpg 校验失败，可能是仓库收录的头像已损坏。
[========================================] 3682/3682 [100%] in 0:05:01 (12.19/s)
√ 下载完成

>> 尺寸优化...
!! ./Downloads/沙羅.jpg 可能已损坏，跳过。
!! ./Downloads/美木ななみ.jpg 可能已损坏，跳过。
!! ./Downloads/菊池えりか.jpg 可能已损坏，跳过。
[========================================] 3681/3681 [100%] in 0:01:05 (55.80/s)
√ 优化完成

>> 导入头像...
[=========================!              ] (!) 2339/3681 [64%] in 0:02:50 (13.72/s)
Traceback (most recent call last):
  File "Gfriends Inputer.py", line 509, in <module>
FileNotFoundError: [Errno 2] No such file or directory: './Downloads/沙羅.jpg'

× 未知错误，在配置文件中开启 Debug 可获得错误详情。

**Comment by xinxin8816** [comment]
已修复此问题 [v2.81](https://github.com/xinxin8816/gfriends/releases)

**Comment by eternalfor** [comment]
非常感谢回复
