### ISSUE TITLE
部分未收录同名

### ISSUE THREAD

**Issue by nukewarrior** [xinxin8816/gfriends#26]
中文 | 日文(对应)
------------ | -------------
君島美緒 | 君島みお
高橋聖子 | 高橋しょう子
三上悠亞 | 三上悠亜
桃乃木香奈 |  桃乃木かな
宇都宮しをん (RION) | 宇都宮しをん
成瀨心美（心美）| 成瀬心美

以上中文名字是从airav刮削出来的

**Comment by xinxin8816** [comment]
核对了一下，数据库是收录了上述中文译名的
应该是后端出了点bug，使生成的文件树异常
目前已回退后端，之后有空再修复
感谢提醒

**Comment by nukewarrior** [comment]
> 核对了一下，数据库是收录了上述中文译名的
> 应该是后端出了点bug，使生成的文件树异常
> 目前已回退到旧版后端，之后有空再修复此问题
> 感谢提醒

幸苦大佬😊

**Comment by xinxin8816** [comment]
后端问题已修复。

现在起，女友仓库可以匹配到更多曾用艺名和译名，甚至是素人佚名。
如下，使用任一名字均可成功匹配：
```
片 假 名：るいぺち
艺    名：妃月るい
英 文 名：Hiduki Rui
素人佚名：Rui
简中译名：妃月由衣
繁中译名：妃月留衣
曾 用 名：川島今日子、如月るい、日向美月、森平みさき、石原美紀、紀月るい
```
