### ISSUE TITLE
女友仓库返回了一个错误：404

### ISSUE THREAD

**Issue by waahaa** [xinxin8816/gfriends#27]
设置：AI_Fix = 否

报错：

Gfriends Inputer v2.81
https://git.io/gfriends

√ 连接 Emby / Jellyfin 服务器成功
   演职人员：1491人

× 女友仓库返回了一个错误：404..
× 用户强制停止或已知错误。
按任意键退出程序...

**Comment by xinxin8816** [comment]
已修复该问题：[v2.82](https://github.com/xinxin8816/gfriends/releases)
