### ISSUE TITLE
仓库有备份吗？

### ISSUE THREAD

**Issue by MCZSR** [xinxin8816/gfriends#29]
请问下仓库有备份吗？更新后忘了改设置，直接覆盖了，新的头像简直没法看啊。。。。

**Comment by xinxin8816** [comment]
大版本更新的历史记录：https://github.com/xinxin8816/gfriends/tags
所有的历史记录：https://github.com/xinxin8816/gfriends/commits/master

另外哪些演员的新头像没法看，请指明一下谢谢。

**Comment by xinxin8816** [comment]
意识到问题了，已修复

**Comment by MCZSR** [comment]
> 意识到问题了，已修复

newbility，响应这么迅速
