### ISSUE TITLE
文件树多对一问题

### ISSUE THREAD

**Issue by laoyang945** [xinxin8816/gfriends#30]
"Megumi Ousawa/Ohsawa.jpg": "大澤恵.jpg"
应该为
"Megumi Ousawa.jpg": "大澤恵.jpg"
"Megumi Ohsawa.jpg": "大澤恵.jpg"

**Comment by laoyang945** [comment]
还有其他以“/”分隔的别名，不一一列举

**Comment by xinxin8816** [comment]
核查后仅发现你提到的这名演员存在该问题
是数据库收录的别名错误，目前已修正
稍后会生成新文件树
