### ISSUE TITLE
【标注错误】詩音乃らん -> 鈴木真夕

### ISSUE THREAD

**Issue by xjasonlyu** [xinxin8816/gfriends#31]
9194a83c506f811d52d8f8f5051744f2d289e754 Filetree里有几处`詩音乃らん`映射成`鈴木真夕`了

<img width="287" alt="Screen Shot 2021-03-19 at 10 39 58 AM" src="https://user-images.githubusercontent.com/28824352/111724047-835cb280-889f-11eb-8031-54d0fd89b91b.png">

**Comment by xinxin8816** [comment]
已修复，稍后会更新文件树
