### ISSUE TITLE
百度人体分析Qps超限

### ISSUE THREAD

**Issue by HEYANG1995** [xinxin8816/gfriends#35]
百度人体分析提示Qps超限额
![Screenshot_20210703-080601_Via](https://user-images.githubusercontent.com/16134777/124337511-8755db80-dbd5-11eb-8809-28ceb72ade63.png)

**Comment by xinxin8816** [comment]
百度人体分析已变更政策，免费用户有新限制，详情 https://ai.baidu.com/ai-doc/BODY/mk3cpyhfe

**Comment by HEYANG1995** [comment]
那这个Qps可以限制吗？我是用的emby插件刮削，它的并发数高了？

**Comment by xinxin8816** [comment]
@HEYANG1995 Gfriends Inputer 可以限制 QPS，对于其他调用本仓库的项目，请咨询相应项目的作者

**Comment by HEYANG1995** [comment]
好的，谢谢
