### ISSUE TITLE
有的刮削程序会把女友的曾用名也存到nfo文件里，能否做个判断？

### ISSUE THREAD

**Issue by kudouxinyi** [xinxin8816/gfriends#38]
有的刮削程序会把女友的曾用名也存到nfo文件里，这种类型的用JAVnfoMoviesImporter.bundle无法获取到头像，能否做个判断，这种女友名字后面有括号曾用名的，只要匹配到一个就停止匹配，并加上头像？ 或者只匹配括号前的

例如   佐々木恋海（向井恋） 倖田李梨（倖田美梨、岩下美季）

**Comment by xinxin8816** [comment]
Gfriends Inputer 已经你说的这种情况做了失败。对于仓库的其他衍生项目，请联系相应作者处理。

**Comment by kudouxinyi** [comment]
忘记说了，我用的是plex，也可以用Gfriends Inputer解决吗？谢谢

**Comment by xinxin8816** [comment]
Gfriends Inputer 暂不支持 Plex
