### ISSUE TITLE
我新上传两张しらいしゆい的照片，同时这里提交她众多别名，她出演URE-009。

### ISSUE THREAD

**Issue by 4488dsq** [xinxin8816/gfriends#46]
しらいしゆい
白石結衣

別名: 早川なお 柊かえで 坂下かえで

T:153 B:86(E) W:57 H:84

**Comment by 4488dsq** [comment]
还有吉根ゆりあ／よしね ゆりあ
别名：吉根柚莉爱

**Comment by 4488dsq** [comment]
本真ゆり
别名：本真友里

**Comment by 4488dsq** [comment]
七菜原ココ
别名：七栄ここ

**Comment by xinxin8816** [comment]
辛苦了
请转换为 jpg 格式，目前仅支持 jpg 格式的处理

**Comment by 4488dsq** [comment]
> 辛苦了
> 请转换为 jpg 格式，目前仅支持 jpg 格式的处理

收到，我这就改。

**Comment by 4488dsq** [comment]
> 辛苦了
> 请转换为 jpg 格式，目前仅支持 jpg 格式的处理

我是不是在上传照片的时候，填写了女优简介。就不永再这里再提出问题，写清楚女优简介。

斎藤あみり

生年月日　　：2000年1月23日
出身地　　　：静岡県
身長　　　　：159.7cm
スリーサイズ：B85(F)-W59-H88
血液型　　　：O型

**Comment by xinxin8816** [comment]
只需要提出别名就好了，不需要女友简介
女友信息将由隔壁 xslist.org 提供

**Comment by 4488dsq** [comment]
> 只需要提出别名就好了，不需要女友简介
> 女友信息将由隔壁 xslist.org 提供

收到，这次上传的三人，俩人是新人没别名，一人老熟女没别名

**Comment by 4488dsq** [comment]
> 只需要提出别名就好了，不需要女友简介
> 女友信息将由隔壁 xslist.org 提供

找到了一个很全的女优别名汇总站，https://seesaawiki.jp/avsagasou/  ，我把我看到的哪天开个贴发一下？还是你爬虫爬一下。
举例：
渚みつき：https://seesaawiki.jp/avsagasou/d/%bd%ed%a4%df%a4%c4%a4%ad%be%dc%ba%d9
别名:
みつき/みつきちゃん/なぎさ/みき/みゆう/RIKO/みひろ/MITSUKI/しおり/まきちゃん/みぃチャン/ウェンディー/なぎさちゃん/ナナ＆ユカ/NAGISA/Mちゃん/みつ/モモコ/みさき/なぎみつ/Yさん/愛/ミツキ/はるかちゃん/M23ちゃん/さくら/なぎっち/なぎちゃん/

**Comment by 4488dsq** [comment]
> 只需要提出别名就好了，不需要女友简介
> 女友信息将由隔壁 xslist.org 提供

找到了一个很全的女优别名汇总站，https://seesaawiki.jp/avsagasou/ ，我把我看到了就贴发一下？还是你爬虫爬一下。基本把女优出演的fc2的演出用名都给出，和一些其他的片里用名，比javdb全。
举例：
渚みつき：https://seesaawiki.jp/avsagasou/d/%bd%ed%a4%df%a4%c4%a4%ad%be%dc%ba%d9
别名:
みつき/みつきちゃん/なぎさ/みき/みゆう/RIKO/みひろ/MITSUKI/しおり/まきちゃん/みぃチャン/ウェンディー/なぎさちゃん/ナナ＆ユカ/NAGISA/Mちゃん/みつ/モモコ/みさき/なぎみつ/Yさん/愛/ミツキ/はるかちゃん/M23ちゃん/さくら/なぎっち/なぎちゃん/

**Comment by xinxin8816** [comment]
ok，我抽空会处理
________________________________

**Comment by xinxin8816** [comment]
@4488dsq 现在已经集成了 seesaawiki.jp 的别名

**Comment by 4488dsq** [comment]
> @4488dsq 现在已经集成了 seesaawiki.jp 的别名

大佬威武，他那也是人工审核，就差点这两年入行的人名字和别名了
