### ISSUE TITLE
NAS问题

### ISSUE THREAD

**Issue by 18E42D38dFA2** [xinxin8816/gfriends#55]
![屏幕截图 2021-09-23 220802](https://user-images.githubusercontent.com/87431855/134522930-bd4b8e08-b293-4491-aed5-8b9a1b10f5f9.jpg)
如图

**Comment by smilejoker365** [comment]
我也是这样，换windows、Mac、Linux来执行都是无法连接服务器

**Comment by xinxin8816** [comment]
服务器地址/emby/Persons?api_key=APIKEY

替换地址和KEY，用浏览器打开看看是什么
________________________________

**Comment by smilejoker365** [comment]
> g this because you are subscribed to this thread.<img width="1669" alt="截屏2021-09-28 上午10 10 31" src="https://user-images.githubusercontent.com/62318411/135011050-c390e68f-bce0-4274-a0fe-202732aae007.png">
大佬，按照您的方法进入后，是一堆演员的名字什么的

**Comment by xinxin8816** [comment]
> > g this because you are subscribed to this thread.<img alt="截屏2021-09-28 上午10 10 31" width="1669" src="https://user-images.githubusercontent.com/62318411/135011050-c390e68f-bce0-4274-a0fe-202732aae007.png">
> > 大佬，按照您的方法进入后，是一堆演员的名字什么的

这是什么版本的服务器？

**Comment by smilejoker365** [comment]
> > > g this because you are subscribed to this thread.<img alt="截屏2021-09-28 上午10 10 31" width="1669" src="https://user-images.githubusercontent.com/62318411/135011050-c390e68f-bce0-4274-a0fe-202732aae007.png">
> > > 大佬，按照您的方法进入后，是一堆演员的名字什么的
> 
> 这是什么版本的服务器？

群晖套件版，版本是4.6.4.0

**Comment by xinxin8816** [comment]
Ok，我抽空会解决
________________________________

**Comment by 18E42D38dFA2** [comment]
我用的是jellyfin，两边全局代理后可以识别了，不过新的问题是有些头像下载完却没有导入
![1](https://user-images.githubusercontent.com/87431855/135076773-960097da-019d-45c8-a5a8-4dae0dde9579.jpg)
![3](https://user-images.githubusercontent.com/87431855/135076818-83dad3f3-2dca-4007-9ce7-c7718f9f7155.jpg)
![2](https://user-images.githubusercontent.com/87431855/135076848-a9aaee5b-f5be-4e16-8487-22fc3e9b23dd.jpg)

**Comment by xinxin8816** [comment]
> 我用的是jellyfin，两边全局代理后可以识别了，不过新的问题是有些头像下载完却没有导入 ![1](https://user-images.githubusercontent.com/87431855/135076773-960097da-019d-45c8-a5a8-4dae0dde9579.jpg) ![3](https://user-images.githubusercontent.com/87431855/135076818-83dad3f3-2dca-4007-9ce7-c7718f9f7155.jpg) ![2](https://user-images.githubusercontent.com/87431855/135076848-a9aaee5b-f5be-4e16-8487-22fc3e9b23dd.jpg)

到 Jellyfin 控制台的计划任务里刷新演员元数据

**Comment by xinxin8816** [comment]
修复了无法识别演员列表的问题 [v2.91](https://github.com/xinxin8816/gfriends/releases/tag/v2.91)
