### ISSUE TITLE
代理服务器错误 clash已开全局模式，avdv就可以用代理

### ISSUE THREAD

**Issue by shrch** [xinxin8816/gfriends#67]
clash已开全局模式代理服务器错误，本地emby服务器倒是可以连上

**Comment by shrch** [comment]
avdc用全局模式可以连上削挂

**Comment by shrch** [comment]
win10 emby server

**Comment by shrch** [comment]
√ 连接 Emby / Jellyfin 服务器成功
× 连接 Gfriends 女友头像仓库超时，请检查网络连接
× 用户强制停止或已知错误

更换镜像仓库依然错误

**Comment by xinxin8816** [comment]
镜像仓库是中国大陆境内的，不需要代理

**Comment by shrch** [comment]
> 镜像仓库是中国大陆境内的，不需要代理

更换镜像仓库不开代理依然报错啊 百思不得其解
√ 连接 Emby / Jellyfin 服务器成功
× 连接 Gfriends 女友头像仓库超时，请检查网络连接
× 用户强制停止或已知错误

**Comment by xinxin8816** [comment]
截图配置文件

**Comment by 342555393** [comment]
![11](https://user-images.githubusercontent.com/95469903/144570110-6349ebb2-f9b5-4817-9db5-480378fb7cd5.png)
![22](https://user-images.githubusercontent.com/95469903/144570118-062b40c5-06fd-4ac7-bd97-d1e14ff1d342.png)
我也是同样的问题 @xinxin8816

**Comment by xinxin8816** [comment]
Clash的TAP网卡全局有兼容性问题，需要在配置文件额外设置代理

Proxy_Range = ALL
Proxy_Link = http://localhost:7890
________________________________
