### ISSUE TITLE
连接 Gfriends 女友头像仓库超时，请检查网络连接  × 用户强制停止或已知错误。 按任意键退出程序...

### ISSUE THREAD

**Issue by shrch** [xinxin8816/gfriends#68]
Gfriends Inputer v2.91
https://git.io/gfriends

推荐开启全局代理

√ 连接 Emby / Jellyfin 服务器成功
   演职人员：19人

× 连接 Gfriends 女友头像仓库超时，请检查网络连接

× 用户强制停止或已知错误。
按任意键退出程序...

**Comment by xinxin8816** [comment]
请不要多开issue
