### ISSUE TITLE
明里䌷=明里紬=明里つむぎ

### ISSUE THREAD

**Issue by BCYDTZ** [xinxin8816/gfriends#75]
明里䌷=明里紬=明里つむぎ

**Comment by xinxin8816** [comment]
䌷是错误的写法，简体中文里也是紬

不过考虑到确实有不少人用错，所以现也已录入数据库

**Comment by BCYDTZ** [comment]
> 䌷是错误的写法，简体中文里也是紬
> 
> 不过考虑到确实有不少人用错，所以现也已录入数据库

一ノ瀬もも=一之濑桃=百田くるみ=百田胡桃

**Comment by xinxin8816** [comment]
> > 䌷是错误的写法，简体中文里也是紬
> > 不过考虑到确实有不少人用错，所以现也已录入数据库
> 
> 一ノ瀬もも=一之濑桃=百田くるみ=百田胡桃

已收录
