### ISSUE TITLE
为什么我用plex每次碰到Rio（柚木ティナ），头像就无法显示？

### ISSUE THREAD

**Issue by heptagonlin** [xinxin8816/gfriends#81]
为什么我用plex每次碰到Rio（柚木ティナ），头像就无法显示？但是手工把nfo文件里修改未Rio，就可以显示？？麻烦大大指导

**Comment by xinxin8816** [comment]
可能Plex插件没有对这种情况适配，直接把`Rio（柚木ティナ）`作为演员名进行搜索了。
