### ISSUE TITLE
网络访问无问题，但是，校验失败，可能是仓库收录的头像已损坏。

### ISSUE THREAD

**Issue by xmasrain** [xinxin8816/gfriends#86]
![image](https://user-images.githubusercontent.com/58833842/160427520-d7990817-d134-481b-8c0d-44fc316f29f0.png)

**Comment by xinxin8816** [comment]
仓库的头像不会如此大规模损坏，可能是网络问题导致传输的头像不完整，尝试降低下载线程数

**Comment by xmasrain** [comment]
已将线程数修改为1，问题依旧。
![image](https://user-images.githubusercontent.com/58833842/163304559-2ccb0e9a-cbf6-40ba-a2e4-c06e0beb23ae.png)

**Comment by xmasrain** [comment]
config文件截图如下
![image](https://user-images.githubusercontent.com/58833842/163304938-3d6d56fb-7bbb-41f4-a1ca-35e783ee2489.png)

**Comment by xinxin8816** [comment]
使用默认仓库地址，并设置代理试一下

**Comment by jyh9521** [comment]
![QQ截图20220430223157](https://user-images.githubusercontent.com/11244739/166109802-62f50001-ceab-4b41-9909-718b88540a48.png)
同样的问题，目前表现为有些人有头像，有些没有，可以确认网络无任何问题。

**Comment by xinxin8816** [comment]
@jyh9521 使用默认仓库地址，确保 githubusercontant.com 通过了代理，下载不完整则会校验失败

**Comment by jyh9521** [comment]
> 

=_,=就是默认仓库，而且确认https://raw.githubusercontent.com/访问无问题，线程数设置也是1，不知道是什么情况。

**Comment by xinxin8816** [comment]
@jyh9521 每次失败的演员都是一样的么

**Comment by jyh9521** [comment]
> 

=_,=额，所有的都会失败。

**Comment by xinxin8816** [comment]
@jyh9521 那就还是访问问题，或者下载目录无权限写入

**Comment by jyh9521** [comment]
> @jyh9521 那就还是访问问题，或者下载目录无权限写入
![QQ截图20220501120546](https://user-images.githubusercontent.com/11244739/166131750-f63fd302-2970-4b36-b799-deaac5e1b87e.png)
下载文件夹里面有下载好的头像的。

**Comment by xinxin8816** [comment]
@jyh9521 如果头像文件没问题，那无视校验失败的报错就好了

**Comment by jyh9521** [comment]
> @jyh9521 如果头像文件没问题，那无视校验失败的报错就好了

T_T但是导入显示成功，实际上jellyfin里确是有些有头像，有些没头像，23个演员只有6个有头像，其他都是空白的。
![QQ截图20220501120907](https://user-images.githubusercontent.com/11244739/166131849-91f57377-dfd4-417c-a873-e97e81bd02c0.png)
![QQ截图20220501120915](https://user-images.githubusercontent.com/11244739/166131856-de131662-824e-4e88-b21d-6718f020ed3b.png)

**Comment by xinxin8816** [comment]
@jyh9521 抱歉，由于P通道图片兼容性及API接口经常变动的原因，已不再支援 Jellyfin。
你可以转码图片为标准RGB格式后手动上传到 Jellyfin

**Comment by jyh9521** [comment]
> @jyh9521 抱歉，由于P通道图片兼容性及API接口经常变动的原因，已不再支援 Jellyfin。 你可以转码图片为标准RGB格式后手动上传到 Jellyfin

原来是jellyfin的原因，那了解了，感谢解惑。
